version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo0909"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-za0tt2dy5ayn"
s3_prefix = "demo0909"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
